# -*- coding: utf-8 -*-
"""2702371136-Raka Maulana Akbar-Regression (3)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCGaKVLnt2Q5V8nTkoKUoaY1N20GDS-v
"""

import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')

x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))

A = np.vstack([x, np.ones(len(x))]).T

y = y[:, np.newaxis]

alpha = np.dot((np.dot(np.linalg.inv(np.dot(A. T, A)),A.T)) ,y)
print(alpha)

pinv = np.linalg.pinv(A)
alpha = pinv.dot(y)
print(alpha)

alpha = np.linalg.lstsq(A, y, rcond=None) [0]
print(alpha)

x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))

def func(x, a, b):
    y = a*x + b
    return y

alpha = optimize.curve_fit(func, xdata = x, ydata = y) [0]
print(alpha)