# -*- coding: utf-8 -*-
"""2702371136-Raka Maulana Akbar-Numpy.LINALG (2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVdUJoDevU_xqd1-g7en9se1amtSwe77
"""

import numpy as np

A = np.array([[4, 3, -5],
        [-2, -4, 5],
              [8, 8, 0]])

y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)